language: node_js
node_js:
  - "10.16.0"

before_install:
  - npm install -g firebase-tools

script: 
  - echo "npm test temporarily disabled"
  - npm run dist
  - npm run jsdoc
  - npm pack

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh dev
    on:
      branch: support-automatic-release
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/setup_deploy.sh staging
    on:
      branch: support-automatic-release
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_cdn.sh ${FIREBASE_DEV_PROJECT} ${FIREBASE_DEPLOY_TOKEN}
    on:
      branch: support-automatic-release
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_cdn.sh ${FIREBASE_STG_PROJECT} ${FIREBASE_DEPLOY_TOKEN}
    on:
      branch: support-automatic-release
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_cdn.sh ${FIREBASE_PROD_PROJECT} ${FIREBASE_DEPLOY_TOKEN}
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
  - provider: script
    skip_cleanup: true
    script: bash ./_deploy/scripts/deploy_to_npm_com.sh ${NPM_TOKEN}
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+(\.[0-9]+)
