# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

references:
  app_container_config: &app_container_config
    docker:
      - image: circleci/node:10.16.0
        environment:
          PROJECT_ROOT: ~/src/github.com/sony/mapray-js/
    working_directory: ~/src/github.com/sony/mapray-js/

jobs:
  build-mapray-js:
    <<: *app_container_config
    steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

        - run:
            name: Install firebase tools
            working_directory: _deploy
            command: |
              yarn add firebase-tools

        - run:
            name: Install packages
            command: |
              yarn install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        - run:
            name: Build mapray-js
            command: |
              yarn run dist

        - run:
            name: Pack mapray-js
            command: |
               yarn pack

        - persist_to_workspace:
            root: .
            paths:
              - ./

  test-build-document:
      <<: *app_container_config
      steps:
          - attach_workspace:
              at: .

          - run:
              name: build document
              command: |
                yarn jsdoc

  deploy-mapray-js-pro:
      <<: *app_container_config
      steps:
          - attach_workspace:
              at: .

          - run:
              name: Deploy to Firabase production env
              working_directory: _deploy
              command: |
                node_modules/.bin/firebase deploy --project $FIREBASE_PRO_PROJECT --token=$FIREBASE_DEPLOY_TOKEN

          - run:
              name: Authenticate with npm registry
              command: |
                echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

          - run:
              working_directory: _deploy/scripts
              command: |
                ./deploy_to_npm_com.sh


  deploy-mapray-js-stg:
      <<: *app_container_config
      steps:
          - attach_workspace:
              at: .

          - run:
              name: Copy deployed file
              working_directory: _deploy/scripts
              command: |
                ./setup_deploy.sh staging

          - run:
              name: Deploy to Firabase staging env
              working_directory: _deploy
              command: |
                node_modules/.bin/firebase deploy --project $FIREBASE_STG_PROJECT --token=$FIREBASE_DEPLOY_TOKEN

  deploy-mapray-js-dev:
      <<: *app_container_config
      steps:
          - attach_workspace:
              at: .

          - run:
              name: Copy deployed file
              working_directory: _deploy/scripts
              command: |
                ./setup_deploy.sh dev

          - run:
              name: Deploy to Firabase development env
              working_directory: _deploy
              command: |
                node_modules/.bin/firebase deploy --project $FIREBASE_DEV_PROJECT --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  test:
    jobs:
      - build-mapray-js:
          filters:
            tags:
              only: /.*/
      - test-build-document:
          requires:
            - build-mapray-js
          filters:
            tags:
              only: /.*/
      - deploy-mapray-js-dev:
          requires:
            - build-mapray-js
          filters:
            branches:
              only: master
      - deploy-mapray-js-stg:
          requires:
            - deploy-mapray-js-dev
          filters:
            branches:
              only: master
      - deploy-mapray-js-pro:
          requires:
            - build-mapray-js
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
